# Generated by Django 2.2.7 on 2019-12-12 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(db_column='titulo', max_length=50, unique=True, verbose_name='titulo')),
                ('genero', models.TextField(db_column='genero', max_length=50, verbose_name='genero')),
                ('duracion', models.IntegerField(db_column='duracion', verbose_name='duracion')),
                ('descripcion', models.TextField(db_column='descripcion', max_length=500, verbose_name='descripcion')),
                ('stock', models.IntegerField(db_column='stock', verbose_name='stock')),
            ],
        ),
        migrations.CreateModel(
            name='Renta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True, verbose_name='fecha')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='IdUsuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel_renta.Pelicula', verbose_name='IdPelicula')),
                ('id_renta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel_renta.Renta', verbose_name='IdRenta')),
            ],
            options={
                'verbose_name': 'DetalleRenta',
                'verbose_name_plural': 'DetalleRentas',
            },
        ),
    ]
